Added failing condition to deploys

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -23,6 +23,11 @@ jobs:
             git pull
             echo "Building container image..."
             podman build -t onboarding-info:latest .
+            if [[ $? -ne 0 ]] ; then
+              echo "Failed, Cleaning up..."
+              podman image ls -a | grep '<none>' | awk '{print $3}' | xargs podman rmi -f
+              exit 1
+            fi
             echo "Shutting down and deleting old containers..."
             podman-compose down
             echo "Bringing up new containers with the latest released code..."
diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -34,6 +34,11 @@ jobs:
             cp .previewConfigs/devnuxt.config.js ./nuxt.config.js
             echo "Building container image..."
             podman build -t onboarding-info-preview:latest .
+            if [[ $? -ne 0 ]] ; then
+              echo "Failed, Cleaning up..."
+              podman image ls -a | grep '<none>' | awk '{print $3}' | xargs podman rmi -f
+              exit 1
+            fi
             echo "Using preview podman configs..."
             cd .previewConfigs
             echo "Shutting down and deleting old previews..."
